### ISSUE TITLE
angular error

### ISSUE THREAD

**Issue by eugenioclrc** [AlexYankee/ionic-webpack-starter#1]
Hi, nice boiler template.

After i compile it with ./dev-server im getting this error;
Uncaught Error: [$injector:unpr] Unknown provider: $$asyncCallbackProvider <- $$asyncCallback <- $animate <- $compile
http://errors.angularjs.org/1.4.3/$injector/unpr?p0=%24%24asyncCallbackProvider%20%3C-%20%24%24asyncCallback%20%3C-%20%24animate%20%3C-%20%24compile

**Comment by AMar4enko** [comment]
@eugenioclrc, hi! Hmm, looks like you got wrong angular-animate (or angular itself) version installed somehow.
Make sure u have angular-animate and angulare of the same version (like 1.4.3).

**Comment by eugenioclrc** [comment]
ok, thanks!

2015-10-07 12:11 GMT-03:00 AlexYankee notifications@github.com:

> @eugenioclrc https://github.com/eugenioclrc, hi! Hmm, looks like you
> got wrong angular-animate (or angular itself) version installed somehow.
> Make sure u have angular-animate and angulare of the same version (like
> 1.4.3).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AlexYankee/ionic-webpack-starter/issues/1#issuecomment-146225409
> .

## 

_May the source be with you._
